version: "3"

# There are 3 services (i.e., containers): the 3 servers
services:

  server1:

    build: server1/
    
    #The command to execute "python ./server.py" (so, once image is created)
    command: python ./server1.py
    ports:
      - 3000:3000

  server2:

    build: server2/
    
    #The command to execute "python ./server.py" (so, once image is created)
    command: python ./server2.py
    ports:
      - 8001:8001    

  server3:

    build: server3/
    #The command to execute "python ./server.py" (so, once image is created)

    command: python ./server3.py
    ports:
      - 4000:4000

  




  