version: "3"

# There are 2 services (i.e., containers): the client and the server. 
services:

  server:

    build: server/
    #The command to execute "python ./server.py" (so, once image is created)
    command: python ./server.py
    ports:
      - 3000:3000

  client:

    build: client/
    #The command to execute "python ./client.py" (so, once image is created). 
    command: python ./client.py
    #Defines the network type 
    #So the container can access to the 'localhost' of the computer.
    network_mode: host
    #Forces the 'client' container to wait until the 'server' container is ready.
    depends_on:
      - server