version: "3"

# There are 6 services (i.e., containers): the client and the server. 
services:

  server1:

    build: server1/
    
    #The command to execute "python ./server.py" (so, once image is created)
    command: python ./server1.py
    ports:
      - 3000:3000

  server2:

    build: server2/
    
    #The command to execute "python ./server.py" (so, once image is created)
    command: python ./server2.py
    ports:
      - 8001:8001    

  server3:

    build: server3/
    #The command to execute "python ./server.py" (so, once image is created)

    command: python ./server3.py
    ports:
      - 4000:4000

  client:

    build: client/
    
    #Executes "python ./client.py" (so, once image is created). 
    command: python ./client.py
    
    #Defines the network type 
    #So the container can access to the 'localhost' of the computer.
    network_mode: host
    
    #Forces the 'client' container to wait until the 'server' container is ready.
    depends_on:
      - server1
      - server2 # remove this!




  